apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: campusconnect-tls
  namespace: campusconnect
spec:
  secretName: campusconnect-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: sait.campusconnect.it.com
  dnsNames:
  - sait.campusconnect.it.com