apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: campusconnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets: 
        - name: acr-auth
      containers:
        - name: frontend
          image: campusconnectacr.azurecr.io/campusconnect-frontend:1.0
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_FIREBASE_API_KEY
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_FIREBASE_APP_ID
            - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
            - name: NEXT_PUBLIC_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_BACKEND_URL
            - name: NEXT_PUBLIC_CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_CLIENT_URL
            - name: NEXT_PUBLIC_IMGBB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_IMGBB_API_KEY
            - name: NEXT_PUBLIC_TINYMCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: NEXT_PUBLIC_TINYMCE_API_KEY

