apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: campusconnect
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80                    # service port exposed to ingress
      targetPort: 3000            # Frontend container port (external)
