name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy CampusConnect
    runs-on: ubuntu-latest

    env:
      ACR_NAME: campusconnectacr
      RESOURCE_GROUP: cc-resource-group
      CLUSTER_NAME: CampusConnectAKS
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    - name: Log in to ACR
      run: az acr login --name $ACR_NAME

    - name: Build and Push Backend Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/campusconnect-backend:${{ env.IMAGE_TAG }} ./server
        docker push $ACR_NAME.azurecr.io/campusconnect-backend:${{ env.IMAGE_TAG }}

    - name: Build and Push Frontend Image
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} \
          --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }} \
          --build-arg NEXT_PUBLIC_FIREBASE_DATABASE_URL=${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }} \
          -t $ACR_NAME.azurecr.io/campusconnect-frontend:${{ env.IMAGE_TAG }} ./client
        docker push $ACR_NAME.azurecr.io/campusconnect-frontend:${{ env.IMAGE_TAG }}

    - name: Update Backend Deployment in AKS
      run: |
        kubectl set image deployment/backend backend=$ACR_NAME.azurecr.io/campusconnect-backend:${{ env.IMAGE_TAG }} -n campusconnect

    - name: Update Frontend Deployment in AKS
      run: |
        kubectl set image deployment/frontend frontend=$ACR_NAME.azurecr.io/campusconnect-frontend:${{ env.IMAGE_TAG }} -n campusconnect

    # Wait for Backend Deployment to be ready
    - name: Wait for API to become healthy
      run: |
        for i in {1..10}; do
          echo "Attempt $i: Checking API health..."
          if curl --fail --silent https://sait.campusconnect.it.com/api/health; then
            echo "✅ API is healthy!"
            exit 0
          fi
          echo "⚠️ Waiting for API to become ready..."
          sleep 5
        done
        echo "❌ API did not become healthy in time."
        exit 1
